Eco-Toner/Eco-Toner/Controllers/AccesoController.cs
using Microsoft.AspNetCore.Mvc;
using Eco_Toner.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;

namespace Eco_Toner.Controllers
{
    public class AccesoController : Controller
    {
        private readonly Models.DB.DbAb6668EcotonerContext _context;

        public AccesoController(Models.DB.DbAb6668EcotonerContext context)
        {
            _context = context;
        }

        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(Usuario oUsuario)
        {
            string usuario = oUsuario.User;
            string clave = oUsuario.Contra;

            var resultadoRol = _context.Database
            .SqlQueryRaw<int>(
                    "EXEC sp_ValidarUsuario @usuario, @contra",
                    new SqlParameter("@usuario", usuario),
                    new SqlParameter("@contra", clave)
                )
                .AsEnumerable()
                .FirstOrDefault();
            var resultadoString = resultadoRol.ToString();

            if (resultadoRol == 1)
            {
                HttpContext.Session.SetString("Usuario", usuario);
                return RedirectToAction("Dashboard", "Dashboard");
            }
            else if (resultadoRol == 2)
            {
                //Si inicia sesion un operador de servicio al cliente ira a su respectivo dashboard
                HttpContext.Session.SetString("Usuario", usuario);
                return RedirectToAction("DashboardSC", "Dashboard");
            }
            else if (resultadoRol == 3)
            {
                //Si inicia sesion un tecnico remoto ira a su respectivo dashboard
                HttpContext.Session.SetString("Usuario", usuario);
                return RedirectToAction("DashboardTR", "Dashboard");
            }
            else if (resultadoRol == 4)
            {
                //Si inicia sesion un tecnico de area ira a su respectivo dashboard
                HttpContext.Session.SetString("Usuario", usuario);
                return RedirectToAction("DashboardTA", "Dashboard");
            }
            else if (resultadoRol == 5)
            {
                //Si inicia sesion un tecnico de area ira a su respectivo dashboard
                HttpContext.Session.SetString("Usuario", usuario);
                return RedirectToAction("DashboardTT", "Dashboard");
            }
            else
            {
                // Usuario no válido: mostrar mensaje de error
                ViewData["Mensaje"] = "Usuario no encontrado.";
                return View();
            }

        }
    }
}

Eco-Toner/Eco-Toner/Views/Acceso/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Form</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- FontAwesome CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <!-- Estilos personalizados -->
    <style>

    body{
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f0f0f0;
    }

    .form-bg {
            width: 100%;
            height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
    }

    .form-container{
            background: linear-gradient(#239b56,#28b463);
    font-family: 'Roboto', sans-serif;
    justify-content: center;
    align-items: center;
    font-size: 0;
    padding: 0 15px;
    border: 1px solid #28b463;
    border-radius: 15px;
    box-shadow: 0 0 20px rgba(0,0,0,0.2);
    max-width:800px;
    display:flex;
    }
    .form-container .form-icon{
        color: #fff;
        font-size: 13px;
        text-align: center;
        text-shadow: 0 0 20px rgba(0,0,0,0.2);
        width: 50%;
        padding: 70px 0;
        vertical-align: top;
        display: inline-block;

        
    }
    .form-container .form-icon i{
        font-size: 124px;
        margin: 0 0 15px;
        display: block;
    }
    .form-container .form-icon .signup a{
        color: #fff;
        text-transform: capitalize;
        transition: all 0.3s ease;
    }
    .form-container .form-icon .signup a:hover{ text-decoration: underline; }
    .form-container .form-horizontal{
        background: rgba(255,255,255,0.99);
        width: 50%;
        padding: 60px 30px;
        margin: -20px 0;
        border-radius: 15px;
        box-shadow: 0 0 20px rgba(0,0,0,0.2);
        display: inline-block;
    }
    .form-container .title{
        color: #454545;
        font-size: 23px;
        font-weight: 900;
        text-align: center;
        text-transform: capitalize;
        letter-spacing: 0.5px;
        margin: 0 0 30px 0;
    }
    .form-horizontal .form-group{
        background-color: rgba(255,255,255,0.15);
        margin: 0 0 15px;
        border: 1px solid #b5b5b5;
        border-radius: 20px;
    }
    .form-horizontal .input-icon{
        color: #b5b5b5;
        font-size: 15px;
        text-align: center;
        line-height: 38px;
        height: 35px;
        width: 40px;
        vertical-align: top;
        display: inline-block;
    }
    .form-horizontal .form-control{
        color: #b5b5b5;
        background-color: transparent;
        font-size: 14px;
        letter-spacing: 1px;
        width: calc(100% - 55px);
        height: 33px;
        padding: 2px 10px 0 0;
        box-shadow: none;
        border: none;
        border-radius: 0;
        display: inline-block;
        transition: all 0.3s;
    }
    .form-horizontal .form-control:focus{
        box-shadow: none;
        border: none;
    }
    .form-horizontal .form-control::placeholder{
        color: #b5b5b5;
        font-size: 13px;
        text-transform: capitalize;
    }
    .form-horizontal .btn{
        color: rgba(255,255,255,0.8);
            background: #117a65;
        font-size: 15px;
        font-weight: 500;
        text-transform: uppercase;
        letter-spacing: 1px;
        width: 100%;
        margin: 0 0 10px 0;
        border: none;
        border-radius: 20px;
        transition: all 0.3s ease;
    }
    .form-horizontal .btn:hover,
    .form-horizontal .btn:focus{
        color: #fff;
        background-color: #58d68d;
        box-shadow: 0 0 5px rgba(0,0,0,0.5);
    }
    .form-horizontal .forgot-pass{
        font-size: 12px;
        text-align: center;
        display: block;
    }
    .form-horizontal .forgot-pass a{
        color: #999;
        transition: all 0.3s ease;
    }
    .form-horizontal .forgot-pass a:hover{
        color: #777;
        text-decoration: underline;
    }

        /*Estilo para la alerta*/
        .alert-danger {
            color: #721c24;
            background-color: #f8d7da;
            border: 1px solid #f5c6cb;
            padding: 10px;
            border-radius: 5px;
            text-align: center;
            font-size: 14px;
            margin-bottom: 15px;
        }

    </style>
</head>
<body>
    <div class="form-bg">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-md-8">
                    <div class="form-container">
                        <div class="form-icon">
                            <i class="fa fa-user-circle"></i>
                        </div>
                        <form class="form-horizontal" action="@Url.Action("Login","Acceso")" method="post">
                            <h3 class="title">Login</h3>
                            <div class="form-group">
                                <span class="input-icon"><i class="fa fa-id-badge"></i></span>
                                <input class="form-control" name="User" type="text" placeholder="Usuario">
                            </div>
                            <div class="form-group">
                                <span class="input-icon"><i class="fa fa-lock"></i></span>
                                <input class="form-control" name="Contra" type="password" placeholder="Contraseña">
                            </div>
                            @{
                                var mensaje = ViewData["Mensaje"] as string;
                            }
                            @if (!string.IsNullOrEmpty(mensaje))
                            {
                                <div class="alert alert-danger" role="alert">
                                    @mensaje
                                </div>
                            }
                            <button class="btn signin">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS y dependencias -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>